name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print Goodbye
        run: echo "Done - Bye"
  second-job:
    runs-on: windows-latest
    needs: first-job
    steps:
      - name: Print Name
        run: echo "Pratyaksh Kumar"
      - name: Country Name
        run: echo "India"
